# Generated by Django 2.2.7 on 2019-12-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='datetime',
            field=models.DateTimeField(default='Dec. 2, 2019, 11 a.m'),
        ),
    ]
