# Generated by Django 2.2.7 on 2019-12-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0002_auto_20191202_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='datetime',
            field=models.DateTimeField(default='Nov. 2, 2019, 11 a.m'),
        ),
    ]
