# Generated by Django 2.2.7 on 2019-12-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_auto_20191202_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
