# Generated by Django 2.2.7 on 2019-11-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_auto_20191130_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
