# Generated by Django 2.2.7 on 2019-12-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_auto_20191130_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['msg_date']},
        ),
    ]
