# Generated by Django 2.2.7 on 2019-12-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_auto_20191202_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='msg',
            field=models.CharField(max_length=102),
        ),
    ]
