# Generated by Django 2.2.7 on 2019-12-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_auto_20191204_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='msg',
            field=models.CharField(blank=True, max_length=102, null=True),
        ),
    ]
